apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: h2o-stateful-set
  namespace: ds-h2o
spec:
  serviceName: h2o-service
  podManagementPolicy: "Parallel"
  replicas: 3
  selector:
    matchLabels:
      app: h2o-k8s
  template:
    metadata:
      labels:
        app: h2o-k8s
    spec:
      containers:
      - name: h2o-k8s
        image: h2oai/h2o-open-source-k8s:latest
        resources:
          requests:
            memory: "4Gi"
        ports:
          - containerPort: 54321
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /kubernetes/isLeaderNode
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
        env:
        - name: H2O_KUBERNETES_SERVICE_DNS
          value: h2o-service.<namespace-name>.svc.cluster.local
        - name: H2O_NODE_LOOKUP_TIMEOUT
          value: '180'
        - name: H2O_NODE_EXPECTED_COUNT
          value: '3'
        - name: H2O_KUBERNETES_API_PORT
          value: '8081'