apiVersion: training.example.com/v1
kind: TrainingJob
metadata:
  name: example-trainingjob
spec:
  replicas: 3
  procpernode: 2
  image: "my-training-image:v1"
  labelSelector:
    matchLabels:
      component: training
