apiVersion: training.azure.kube.trainer/v1
kind: TrainingJob
metadata:
  name: example-trainingjob
spec:
  replicas: 2
  procpernode: 1
  image: "ishaansehgal99/dist-training"
  labelSelector:
    matchLabels:
      component: training
