---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - training.azure.kube.trainer
  resources:
  - trainingjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.azure.kube.trainer
  resources:
  - trainingjobs/finalizers
  verbs:
  - update
- apiGroups:
  - training.azure.kube.trainer
  resources:
  - trainingjobs/status
  verbs:
  - get
  - patch
  - update
